AWSTemplateFormatVersion: 2010-09-09
# This CloudFormation is used for Data4Business project. The AWS environnement is created in eu-west-1
Mappings:
 #  This is the Amazon Linux 2 AMI.  Adjust these values as needed, they can change a few times per year:
  AmazonLinuxAMI:
    eu-west-1:
      AMI: ami-07ea61f0216dae1e6    # Ireland 
Parameters:
#  QGISInstanceKeyPair:
#    Type: "AWS::EC2::KeyPair::KeyName"
#    Default: QGISInstanceKeyPair
  NumberOfAZs:
    Type: Number
    AllowedValues:
    - 1
    - 2
    - 3
    Default: 1
    Description:  How many Availability Zones do you wish to utilize?
Resources:
  QGISInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [ AmazonLinuxAMI, !Ref "AWS::Region", AMI]  # lookup from AMI map
      InstanceType: t2.small                          
      NetworkInterfaces:
      - DeviceIndex: '0'
        SubnetId: !ImportValue Data4EnergyAPP1              
        AssociatePublicIpAddress: false                
        GroupSet: [ !ImportValue PrivateSecurityGroup1]             # Plug in the security group
     #   KeyName: "QGISInstanceKeyPair"
      SourceDestCheck: true 
      Tags:
      - 
        Key: Name
        Value: QGISInstance
