AWSTemplateFormatVersion: 2010-09-09
# This CloudFormation is used for Data4Business project. The AWS environnement is created in eu-west-1
Mappings:
 #  This is the Amazon Linux 2 AMI.  Adjust these values as needed, they can change a few times per year:
  AmazonLinuxAMI:
    eu-west-1:
      AMI: ami-07ea61f0216dae1e6    # Ireland 
Parameters:
#  QGISInstanceKeyPair:
#    Type: "AWS::EC2::KeyPair::KeyName"
#    Default: QGISInstanceKeyPair
  NumberOfAZs:
    Type: Number
    AllowedValues:
    - 1
    - 2
    - 3
    Default: 1
    Description:  How many Availability Zones do you wish to utilize?
Resources:
  QGISInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [ AmazonLinuxAMI, !Ref "AWS::Region", AMI]  # lookup from AMI map
      InstanceType: t2.small    
      KeyName: "QGISInstanceKeyPair"
      NetworkInterfaces:
      - DeviceIndex: '0'
        SubnetId: !ImportValue Data4EnergyAPP1      
        AssociatePublicIpAddress: false                
        GroupSet: [ !ImportValue PrivateSecurityGroup1]             # Plug in the security group
      SourceDestCheck: true 
      Tags:
      - 
        Key: Name
        Value: QGISInstance
#Target Group 
  TargetGroupApps1:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    DependsOn: QGISInstance
    Properties: 
      Name: TargetGroupApp1
      VpcId: !ImportValue VPCApps  
      Port: 80
      Protocol: TCP
      TargetType: instance 
      Targets: 
        - Id: !Ref QGISInstance
   #NLB in VPCAPPS
  NLBApps1:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties: 
      IpAddressType: ipv4
      Name: NLBVPCApps
      Scheme: internal
      Subnets: "Data4EnergyAPP1"
      Type: network
 #Listeners for NLBVPCApps
  NLBListernerApps1:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
       - Type: forward
         TargetGroupArn: !Ref TargetGroupApps1
      LoadBalancerArn: !Ref NLBApps1
      Port: 80
      Protocol: TCP
#Output section expected      
Outputs:
  QGISInstance:
    Description: Instance for QGIS
    Value: !Ref QGISInstance
    Export:
      Name: QGISInstance
